print('hello world')
print('hello world111')
print('hello worldsss')
print('hello worldzzzz')
print('hello worldsss123')
print('hello worldsss123')
print('hello worldsss123')
print('Nastya vkusnaya!')
#whdafagfawkfg
a = int ()
b = int (23)
